version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    env_file: .env
    environment:
            - node_env=$NODE_ENV
    depends_on:
        - mysql2
    ports:
        - "5000:5000"

  mysql2:
    image: mysql:5.6
    container_name: mysql2
    ports:
        - "3306:3306"
    env_file: .env
    environment:
       - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
       - MYSQL_DATABASE=$MYSQL_DATABASE 
    command: mysqld --max_allowed_packet=32505856 --explicit_defaults_for_timestamp --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        - ./dados-mysql:/var/lib/mysql
    networks:
        - default

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin2
      links:
          - mysql2:db
      ports:
          - "81:80"
      restart: always
      env_file: .env
      environment:
          - PMA_HOST=$PMA_HOST
          - PMA_PORT=$PMA_PORT
          - UPLOAD_LIMIT=$UPLOAD_LIMIT
volumes:
  dados-mysql:

